# Generated by Django 2.1 on 2019-01-13 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NatalHoroscope',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permalink', models.CharField(max_length=12, unique=True)),
                ('first_name', models.CharField(max_length=30, verbose_name='First name')),
                ('middle_name', models.CharField(max_length=30, verbose_name='Middle name')),
                ('last_name', models.CharField(max_length=30, verbose_name='Last name')),
                ('date_of_birth', models.DateField(verbose_name='Date of Birth')),
                ('time_of_birth', models.DateTimeField(verbose_name='Time of Birth')),
                ('place_of_birth', models.CharField(max_length=80, verbose_name='Place of Birth')),
                ('current_location', models.CharField(max_length=80, verbose_name='current_location')),
                ('message', models.CharField(max_length=200)),
            ],
        ),
    ]
